### ISSUE TITLE
hyperf 框架版本 3.1, php 版本 8.2.17无法安装

### ISSUE THREAD

**Issue by aimating** [hyperf/graphql#5]
hyperf/framework：^3.1
php: version 8.2.17

  Problem 1
    - hyperf/graphql[v3.1.0-alpha.1, ..., 3.1.x-dev] require thecodingmachine/graphqlite ^3.0 -> satisfiable by thecodingmachine/graphqlite[v3.0.0, ..., 3.1.x-dev].
    - thecodingmachine/graphqlite[v3.1.3, ..., 3.1.x-dev] require ecodev/graphql-upload ^4.0 -> satisfiable by ecodev/graphql-upload[4.0.0, 4.1.0].
    - thecodingmachine/graphqlite[v3.0.0, ..., v3.1.2] require phpdocumentor/reflection-docblock ^4.3 -> satisfiable by phpdocumentor/reflection-docblock[4.3.0, ..., 4.3.4].
    - ecodev/graphql-upload 4.0.0 requires php ^7.1 -> your php version (8.2.17) does not satisfy that requirement.
    - ecodev/graphql-upload 4.1.0 requires php ^7.2 -> your php version (8.2.17) does not satisfy that requirement.
    - phpdocumentor/reflection-docblock[4.3.0, ..., 4.3.4] require php ^7.0 -> your php version (8.2.17) does not satisfy that requirement.
    - Root composer.json requires hyperf/graphql ^3.1 -> satisfiable by hyperf/graphql[v3.1.0-alpha.1, ..., 3.1.x-dev].

**Comment by limingxinleo** [comment]
graphql 不支持 hyperf 3.1
